Repository GeoGuesSUUU/GeoGuesSUUU, pull requests merged in 2022-12, with the labels that each got.

#3 add database doc
  docs/database.md
Labels: documentation

#8 user api fixed
  config/packages/security.yaml
  src/Controller/UserApiController.php
  src/Entity/UserEditDTO.php
  src/Utils/ApiResponse.php
Labels: API, FIX

#22 Encrypt User password + install JWT system + JWT documentation
  .env.example
  .gitignore
  README.md
  composer.json
  composer.lock
  config/bundles.php
  config/packages/lexik_jwt_authentication.yaml
  config/packages/security.yaml
  config/routes.yaml
  docs/img/token-postman.png
  docs/jwt.md
  src/Controller/UserApiController.php
  src/Controller/UserController.php
  src/Entity/User.php
  symfony.lock
Labels: documentation, API, security

#28 fix admin UI
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/UserEditType.php
  src/Form/UserType.php
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: ADMIN front

#36 Feat/add prefix admin
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Form/RegistrationFormType.php
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
Labels: FIX, ADMIN front
