Repository GeoGuesSUUU/GeoGuesSUUU, pull requests merged in 2023-01, with the labels that each got.

#33 Game api
  docs/database.md
  src/Controller/GameApiController.php
  src/Entity/Game.php
  src/Entity/Level.php
  src/Exception/GameNotFoundApiException.php
  src/Exception/GameNotValidApiException.php
Labels: API

#38 Fix user api connexion
  config/packages/security.yaml
  public/bundles/nelmioapidoc/style.css
  src/Controller/UserApiController.php
Labels: API

#45 add fixture doc
  docs/fixture.md
Labels: documentation

#69 Create LICENSE 2023
  LICENSE
Labels: documentation, security

#43 Fix country api + api content json
  src/Controller/CountryApiController.php
  src/Controller/UserApiController.php
  src/Entity/Country.php
Labels: API, FIX

#47 (> #42, #43) Update entity
  docs/database.md
  migrations/Version20221223100116.php
  migrations/Version20221225180811.php
  src/Controller/CountryApiController.php
  src/Entity/Country.php
  src/Entity/Game.php
  src/Entity/Level.php
  src/Entity/User.php
Labels: documentation, Entity/Database, Has PR dependency

#49 (> #38, #47) Add API endpoint `/api/user/login` + CORS
  .env.example
  config/packages/security.yaml
  public/index.php
  src/Controller/CountryApiController.php
  src/Controller/UserApiController.php
  src/Entity/User.php
Labels: API, Has PR dependency

#56 (> #49) Item API + User Inventory API + User personal data Management + User Level System
  migrations/Version20221221094532.php
  src/Controller/ItemApiController.php
  src/Controller/UserApiController.php
  src/Controller/UserItemApiController.php
  src/Entity/CountryItem.php
  src/Entity/ItemType.php
  src/Entity/User.php
  src/Entity/UserItem.php
  src/Exception/ItemTypeNotFoundApiException.php
  src/Exception/ItemTypeNotValidApiException.php
  src/Exception/UserForbiddenAccessApiException.php
  src/Utils/LevelManager.php
Labels: features, API, security, Has PR dependency

#64 (> #56) Update Country for MainGame (Entity + Endpoint)
  migrations/Version20221227142601.php
  migrations/Version20221227221248.php
  migrations/Version20221228142513.php
  src/Controller/CountryApiController.php
  src/Controller/CountryItemApiController.php
  src/Entity/ClaimRewards.php
  src/Entity/Country.php
  src/Entity/Effect.php
  src/Entity/ItemType.php
  src/Entity/ItemsQuantity.php
  src/Entity/User.php
  src/Repository/CountryItemRepository.php
  src/Repository/CountryRepository.php
  src/Repository/UserRepository.php
  src/Service/CountryService.php
  src/Service/UserService.php
  src/Utils/EffectType.php
  src/Utils/ItemTypeType.php
  src/Utils/Rarity.php
Labels: features, API, FIX, Entity/Database, Service, Has PR dependency

#70 (> #64) Shield Restore Command for Scheduler
  docs/command.md
  src/Command/ShieldRestoreCommand.php
  src/Service/CountryService.php
Labels: features, Service, Has PR dependency

#74 Country default flag + Unique iso code
  src/Controller/CountryApiController.php
  src/Entity/Country.php
  src/Service/CountryService.php
Labels: API, Entity/Database

#75 (> #74) Country - Initialize Command
  docs/command.md
  src/Command/CountriesInitCommand.php
  src/Controller/CountryApiController.php
  src/Entity/Country.php
  src/Service/CountryService.php
  src/Utils/CountriesISO.php
Labels: Entity/Database, Has PR dependency, Command

#77 Fix: attack when country not has owner
  src/Service/CountryService.php
Labels: FIX, Service

#78 manage roles
  src/Form/UserEditType.php
  src/Form/UserType.php
Labels: features

#83 create all form
  src/Controller/CityController.php
  src/Controller/CountryController.php
  src/Controller/GameController.php
  src/Controller/LevelController.php
  src/Controller/RegionController.php
  src/Controller/ScoreController.php
  src/Form/CityType.php
  src/Form/GameType.php
  src/Form/LevelType.php
  src/Form/RegionType.php
  src/Form/ScoreType.php
  templates/city/_delete_form.html.twig
  templates/city/_form.html.twig
  templates/city/edit.html.twig
  templates/city/index.html.twig
  templates/city/new.html.twig
  templates/city/show.html.twig
  templates/game/_delete_form.html.twig
  templates/game/_form.html.twig
  templates/game/edit.html.twig
  templates/game/index.html.twig
  templates/game/new.html.twig
  templates/game/show.html.twig
  templates/level/_delete_form.html.twig
  templates/level/_form.html.twig
  templates/level/edit.html.twig
  templates/level/index.html.twig
  templates/level/new.html.twig
  templates/level/show.html.twig
  templates/region/_delete_form.html.twig
  templates/region/_form.html.twig
  templates/region/edit.html.twig
  templates/region/index.html.twig
  templates/region/new.html.twig
  templates/region/show.html.twig
  templates/score/_delete_form.html.twig
  templates/score/_form.html.twig
  templates/score/edit.html.twig
  templates/score/index.html.twig
  templates/score/new.html.twig
  templates/score/show.html.twig
Labels: features, ADMIN front

#86 add admin page + header
  public/assets/img/earth-icon.svg
  public/assets/styles.css
  src/Controller/ItemTypeController.php
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/header/header.html.twig
  templates/security/login.html.twig
Labels: ADMIN front

#87 fix support shield+
  src/Service/CountryService.php
Labels: FIX

#88 [WIP] Form style
  public/assets/styles.css
  src/Form/CountryType.php
  src/Form/ItemTypeType.php
  src/Form/LevelType.php
  src/Form/ScoreType.php
  templates/city/_delete_form.html.twig
  templates/city/_form.html.twig
  templates/city/edit.html.twig
  templates/city/index.html.twig
  templates/city/new.html.twig
  templates/city/show.html.twig
  templates/country/_delete_form.html.twig
  templates/country/_form.html.twig
  templates/country/edit.html.twig
  templates/country/index.html.twig
  templates/country/new.html.twig
  templates/country/show.html.twig
  templates/game/_delete_form.html.twig
  templates/game/_form.html.twig
  templates/game/edit.html.twig
  templates/game/index.html.twig
  templates/game/new.html.twig
  templates/game/show.html.twig
  templates/item_type/_delete_form.html.twig
  templates/item_type/_form.html.twig
  templates/item_type/edit.html.twig
  templates/item_type/index.html.twig
  templates/item_type/new.html.twig
  templates/item_type/show.html.twig
  templates/level/_delete_form.html.twig
  templates/level/_form.html.twig
  templates/level/edit.html.twig
  templates/level/index.html.twig
  templates/level/new.html.twig
  templates/level/show.html.twig
  templates/region/_delete_form.html.twig
  templates/region/_form.html.twig
  templates/region/edit.html.twig
  templates/region/index.html.twig
  templates/region/new.html.twig
  templates/region/show.html.twig
  templates/score/_delete_form.html.twig
  templates/score/_form.html.twig
  templates/score/edit.html.twig
  templates/score/index.html.twig
  templates/score/new.html.twig
  templates/score/show.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: ADMIN front

#94 fix header
  public/assets/styles.css
  templates/header/header.html.twig
Labels: ADMIN front

#93 fix user edit form
  src/Controller/UserController.php
  src/Entity/Country.php
  src/Service/CountryService.php
  templates/country/index.html.twig
Labels: invalid, ADMIN front

#95 fix bug
  src/Entity/Game.php
Labels: ADMIN front

#96 update item form
  src/Form/ItemTypeType.php
  templates/item_type/_form.html.twig
  templates/item_type/edit.html.twig
  templates/item_type/index.html.twig
  templates/item_type/new.html.twig
  templates/item_type/show.html.twig
Labels: ADMIN front

#97 Handling fantastic (unique) item + Update UserItemAPIController
  src/Controller/CountryApiController.php
  src/Controller/UserItemApiController.php
  src/Exception/ItemFantasticAlreadyExistApiException.php
  src/Service/UserService.php
Labels: API, Service

#104 add img to User
  migrations/Version20230106185659.php
  src/Entity/User.php
Labels: Entity/Database, migration

#109 Fix API error404
  src/EventSubscriber/ExceptionSubscriber.php
Labels: API, FIX

#110 fix style + date time
  public/assets/styles.css
  src/Form/CountryType.php
  src/Form/ScoreType.php
  templates/city/index.html.twig
  templates/country/_form.html.twig
  templates/country/index.html.twig
  templates/country/show.html.twig
  templates/game/index.html.twig
  templates/item_type/_form.html.twig
  templates/item_type/edit.html.twig
  templates/item_type/index.html.twig
  templates/level/index.html.twig
  templates/region/index.html.twig
  templates/score/_form.html.twig
  templates/score/index.html.twig
  templates/user/index.html.twig
Labels: ADMIN front

#124 update button + remove useless field
  templates/city/index.html.twig
  templates/country/index.html.twig
  templates/game/index.html.twig
  templates/item_type/index.html.twig
  templates/level/index.html.twig
  templates/region/index.html.twig
  templates/score/index.html.twig
  templates/user/index.html.twig
Labels: ADMIN front

#125 Update chat reconnect websocket
  templates/websocket/index.html.twig
Labels: Server, Server - Chat

#127 add locale field
  src/Form/UserType.php
  templates/user/_form.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: ADMIN front

#128 add effect + user field
  public/assets/scripts.js
  public/assets/styles.css
  src/Form/CountryType.php
  templates/base.html.twig
  templates/country/_form.html.twig
  templates/country/show.html.twig
  templates/item_type/_form.html.twig
Labels: ADMIN front

#129 add user + level field
  src/Form/ScoreType.php
  templates/score/_form.html.twig
Labels: ADMIN front

#130 add game field
  src/Form/LevelType.php
  templates/level/_form.html.twig
Labels: ADMIN front

#133 Feat/display img
  public/assets/img/items/item_default.svg
  public/assets/styles.css
  templates/city/index.html.twig
  templates/city/show.html.twig
  templates/country/index.html.twig
  templates/country/show.html.twig
  templates/game/index.html.twig
  templates/game/show.html.twig
  templates/item_type/index.html.twig
  templates/item_type/show.html.twig
  templates/region/index.html.twig
  templates/region/show.html.twig
Labels: ADMIN front

#134 translate admin page + delete duplicate field effect country form
  templates/admin/index.html.twig
  templates/country/show.html.twig
  templates/header/header.html.twig
Labels: ADMIN front

#135 Feat/add game fixtures + upload .tsv in item form
  src/Controller/ItemTypeController.php
  src/DataFixtures/GameFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Effect.php
  src/Entity/Game.php
  src/Entity/ItemType.php
  src/Entity/Level.php
  src/Form/CountryType.php
  templates/country/_form.html.twig
  templates/game/index.html.twig
  templates/game/show.html.twig
  templates/item_type/_add_levels.html.twig
  templates/item_type/index.html.twig
Labels: ADMIN front, FIXTURE

#136 Game/find the flag
  README.md
  config/packages/monolog.yaml
  docs/game-find-the-flag.md
  public/assets/game-find-the-flag.css
  public/assets/img/items/flag.svg
  public/assets/js/find-the-flag.js
  src/Command/FindTheFlagServerCommand.php
  src/Controller/WebSocket/FindTheFlagWebSocketController.php
  src/Entity/FindTheFlagAnswer.php
  src/Entity/FindTheFlagRoom.php
  src/Entity/FindTheFlagUserGuess.php
  src/Entity/GameConnection.php
  src/Entity/GameRoom.php
  src/Entity/GameRoomMember.php
  src/Entity/User.php
  src/Exception/GameNotStartException.php
  src/Service/ChatService.php
  src/Service/FindTheFlagGameService.php
  src/Service/GameRoomService.php
  src/Service/UserService.php
  src/Service/WebSocketService.php
  src/Utils/CountriesISO.php
  src/Utils/GameRoomVisibility.php
  src/WebSocket/FindTheFlagGameHandler.php
  templates/websocket/game.html.twig
Labels: features, Service, Server, Server - Game

#140 Turn Effect to Entity
  migrations/Version20230114131817.php
  src/Controller/API/CountryApiController.php
  src/Controller/API/ItemApiController.php
  src/Entity/Country.php
  src/Entity/Effect.php
  src/Entity/ItemType.php
  src/Repository/EffectRepository.php
  src/Service/CountryService.php
Labels: API, FIX, Entity/Database, migration

#142 add new store entity
  migrations/Version20230119172305.php
  src/Entity/StoreItem.php
  src/Repository/StoreItemRepository.php
  src/Utils/StoreItemType.php
Labels: Entity/Database

#145 Add ITEM Price
  migrations/Version20230121161016.php
  src/Controller/ItemTypeController.php
  src/Entity/Country.php
  src/Entity/ItemType.php
  src/Form/ItemTypeType.php
  templates/item_type/_form.html.twig
  templates/item_type/index.html.twig
Labels: features, ADMIN front, Entity/Database, migration

#149 Fix/user unsigned+error handler
  migrations/Version20230121205032.php
  src/Entity/User.php
  src/EventSubscriber/ExceptionSubscriber.php
Labels: FIX, 🔒 security, Entity/Database, migration

#159 fix game fixture + update ftf template
  src/Controller/WebSocket/FindTheFlagWebSocketController.php
  src/DataFixtures/GameFixtures.php
  templates/websocket/game.html.twig
Labels: FIX, FIXTURE

#162 fix store endpoint bug + up api doc
  src/Controller/API/StoreApiController.php
Labels: FIX

#163 fix score group
  src/Controller/API/UserApiController.php
  src/Entity/Game.php
  src/Entity/Level.php
  src/Entity/Score.php
Labels: FIX

#164 fix add equipment
  src/Controller/API/CountryItemApiController.php
  src/Service/CountryService.php
Labels: FIX

#166 Store page
  migrations/Version20230128132015.php
  public/assets/store-page.css
  public/assets/styles.css
  src/Controller/StoreController.php
  src/Controller/StoreItemController.php
  src/Entity/ItemType.php
  src/Entity/StoreItem.php
  src/Form/StoreItemType.php
  templates/header/header.html.twig
  templates/store/index.html.twig
  templates/store_item/_delete_form.html.twig
  templates/store_item/_form.html.twig
  templates/store_item/edit.html.twig
  templates/store_item/index.html.twig
  templates/store_item/new.html.twig
  templates/store_item/show.html.twig
Labels: features, ADMIN front, migration

#169 Find the Flag - multiplayer
  docs/game-find-the-flag.md
  public/assets/js/find-the-flag.js
  src/Entity/FindTheFlagRoom.php
  src/Entity/GameRoom.php
  src/Entity/GameRoomMember.php
  src/Service/FindTheFlagGameService.php
  src/Service/GameRoomService.php
  src/WebSocket/FindTheFlagGameHandler.php
  templates/websocket/game.html.twig
Labels: features, API, ADMIN front, Server, 🕹️ Server - Game

#170 Fix API store item & more
  src/Controller/API/StoreApiController.php
  src/Controller/API/UserApiController.php
  src/Entity/Country.php
  src/Service/StoreService.php
Labels: FIX

#171 Fix Effects
  src/Controller/CountryController.php
  src/Controller/ItemTypeController.php
  src/Entity/Country.php
  src/Form/CountryType.php
  src/Form/EffectType.php
  src/Form/ItemTypeType.php
  templates/country/show.html.twig
  templates/item_type/show.html.twig
Labels: FIX, ADMIN front

#172 Fix/on trend optional
  src/Form/StoreItemType.php
Labels: FIX, ADMIN front

#177 fix locale error
  src/Form/UserEditType.php
Labels: FIX, ADMIN front

#178 add game name in show level
  src/Controller/LevelController.php
  templates/level/show.html.twig
Labels: features, ADMIN front

#179 fix active page
  templates/admin/index.html.twig
  templates/header/header.html.twig
Labels: FIX, ADMIN front

#180 fix level system
  src/Utils/LevelManager.php
Labels: FIX, Service
